/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a test /home/bjorniv/arbeid/endpoint_agent/endpoint_agent/DBusInterface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "test.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class Policy1Adaptor
 */

Policy1Adaptor::Policy1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

Policy1Adaptor::~Policy1Adaptor()
{
    // destructor
}

/*
 * Implementation of adaptor class Usbguard1Adaptor
 */

Usbguard1Adaptor::Usbguard1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

Usbguard1Adaptor::~Usbguard1Adaptor()
{
    // destructor
}

QString Usbguard1Adaptor::getParameter(const QString &name)
{
    // handle method call org.usbguard1.getParameter
    QString value;
    QMetaObject::invokeMethod(parent(), "getParameter", Q_RETURN_ARG(QString, value), Q_ARG(QString, name));
    return value;
}

QString Usbguard1Adaptor::setParameter(const QString &name, const QString &value)
{
    // handle method call org.usbguard1.setParameter
    QString previous_value;
    QMetaObject::invokeMethod(parent(), "setParameter", Q_RETURN_ARG(QString, previous_value), Q_ARG(QString, name), Q_ARG(QString, value));
    return previous_value;
}

