name: Build project with Qmake

on:
  push:
    branches: [ main ]  
  pull_request:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: '6.1.3'
          host: 'linux'
          target: 'desktop'

      - name: Check Qmake version
        run: qmake -v

      - name: Build project
        run: |
          ls
          mkdir build
          cd build
          qmake ..
          make
          
