name: Build project with Qmake

on:
  push:
    branches: [ main ]  
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: '6.1.3'
          host: 'linux'
          target: 'desktop'

      - name: Check Qmake version
        run: qmake -v
        
      - name: Build QtMqtt from source
        run: |
          git clone --branch 6.1.3 https://github.com/qt/qtmqtt
          cd qtmqtt
          mkdir build
          cd build
          qmake .. 
          make 
          make install

      - name: Build project
        run: |
          mkdir build
          cd build
          qmake ..
          make
